#!/usr/bin/env python3
"""Match GitHub 'good first issues' to a developer's interests using an LLM.

Reads the pre-scraped CSV of ranked issues, interactively gathers user
preferences, and makes a single GPT-4o-mini call to find the best matches.

Cost: ~$0.003 per run (single API call with ~20k input tokens).

Requirements:
    - OPENAI_API_KEY environment variable set
    - good_first_issues.csv (generated by scrape_good_first_issues.py)

Usage:
    python3 match_issues.py [--csv FILE] [--top N]
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path

from openai import OpenAI

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_CSV = "good_first_issues.csv"
DEFAULT_TOP_N = 10
MODEL = "gpt-5.5"
MAX_TOKENS = 2000

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class UserProfile:
    """Developer profile gathered interactively."""

    languages: list[str]
    domains: list[str]
    experience: str
    extra_context: str


@dataclass
class IssueSummary:
    """Condensed issue representation for LLM context."""

    index: int
    title: str
    repo: str
    labels: str
    score: float
    stars: int
    comments: int
    body_excerpt: str = ""
    linked_pr_state: str = ""
    is_new: bool = False


# ---------------------------------------------------------------------------
# Interactive user profiling
# ---------------------------------------------------------------------------


def gather_user_profile() -> UserProfile:
    """Interactively ask the user about their preferences."""
    print("\n" + "=" * 60)
    print("  Developer Profile — Tell us about your interests")
    print("=" * 60)

    print("\nWhat programming languages do you know?")
    print("(comma-separated, e.g.: Python, Go, C++, JavaScript)")
    languages_raw = input("> ").strip()
    languages = [lang.strip() for lang in languages_raw.split(",") if lang.strip()]

    print("\nWhat domains or areas interest you?")
    print("(comma-separated, e.g.: testing, CLI tools, networking, docs, UI, DevOps)")
    domains_raw = input("> ").strip()
    domains = [d.strip() for d in domains_raw.split(",") if d.strip()]

    print("\nWhat's your experience level?")
    print("  1. Beginner (new to open source)")
    print("  2. Intermediate (some contributions)")
    print("  3. Advanced (regular contributor)")
    exp_choice = input("> ").strip()
    experience_map = {"1": "beginner", "2": "intermediate", "3": "advanced"}
    experience = experience_map.get(exp_choice, "intermediate")

    print("\nAnything else the matcher should know?")
    print("(e.g.: 'I prefer small fixes', 'interested in Kubernetes', or press Enter to skip)")
    extra = input("> ").strip()

    profile = UserProfile(
        languages=languages,
        domains=domains,
        experience=experience,
        extra_context=extra,
    )

    print(f"\n✓ Profile: {experience} developer")
    print(f"  Languages: {', '.join(languages) or 'any'}")
    print(f"  Interests: {', '.join(domains) or 'any'}")
    if extra:
        print(f"  Notes: {extra}")

    return profile


# ---------------------------------------------------------------------------
# CSV loading
# ---------------------------------------------------------------------------


def load_issues(csv_path: Path) -> list[IssueSummary]:
    """Load issues from the scraped CSV file."""
    issues: list[IssueSummary] = []
    with csv_path.open("r", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for i, row in enumerate(reader, start=1):
            issues.append(IssueSummary(
                index=i,
                title=row["title"],
                repo=row["repo"],
                labels=row["labels"],
                score=float(row["total_score"]),
                stars=int(row["stars"]),
                comments=int(row["comments"]),
                body_excerpt=row.get("body_excerpt", ""),
                linked_pr_state=row.get("linked_pr_state", ""),
                is_new=row.get("is_new", "") == "🆕",
            ))
    return issues


# ---------------------------------------------------------------------------
# LLM matching
# ---------------------------------------------------------------------------


def build_prompt(profile: UserProfile, issues: list[IssueSummary]) -> tuple[str, str]:
    """Build the system and user prompts for the LLM.

    Returns:
        Tuple of (system_prompt, user_prompt).
    """
    system_prompt = (
        "You are a developer-issue matcher. Given a developer's profile and a numbered "
        "list of open source issues, select the best matches. Consider:\n"
        "- Language/technology alignment with the issue's repo and labels\n"
        "- Domain alignment with the developer's interests\n"
        "- Difficulty appropriateness for their experience level\n"
        "- Issue quality (higher score = fresher, less contested)\n\n"
        "Return ONLY valid JSON: an array of objects with fields:\n"
        '  {"issue_number": int, "reason": "brief explanation (1 sentence)"}\n'
        "Ordered from best match to worst. No markdown, no extra text."
    )

    # Compress issues into minimal text to save tokens
    issue_lines: list[str] = []
    for issue in issues:
        line = (
            f"{issue.index}. [{issue.repo}] {issue.title} "
            f"| Labels: {issue.labels} | Score: {issue.score:.0f} "
            f"| Stars: {issue.stars} | Comments: {issue.comments}"
        )
        # Include body excerpt if available for richer context
        if hasattr(issue, 'body_excerpt') and issue.body_excerpt:
            line += f" | Desc: {issue.body_excerpt}"
        issue_lines.append(line)

    user_prompt = (
        f"## Developer Profile\n"
        f"- Languages: {', '.join(profile.languages) or 'any'}\n"
        f"- Interests: {', '.join(profile.domains) or 'any'}\n"
        f"- Experience: {profile.experience}\n"
        f"- Notes: {profile.extra_context or 'none'}\n\n"
        f"## Issues ({len(issues)} total)\n\n"
        + "\n".join(issue_lines)
        + f"\n\nSelect the top {DEFAULT_TOP_N} best-matching issues for this developer."
    )

    return system_prompt, user_prompt


def match_with_llm(
    profile: UserProfile,
    issues: list[IssueSummary],
    top_n: int,
    api_key: str,
) -> list[dict]:
    """Call GPT-4o-mini to match issues to the user profile.

    Returns:
        List of dicts with 'issue_number' and 'reason' fields.
    """
    system_prompt, user_prompt = build_prompt(profile, issues)

    # Update selection count in prompt
    user_prompt = user_prompt.replace(
        f"Select the top {DEFAULT_TOP_N}",
        f"Select the top {top_n}",
    )

    client = OpenAI(api_key=api_key)

    print("\n⏳ Matching issues to your profile (single API call)...")

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        max_completion_tokens=MAX_TOKENS,
    )

    content = response.choices[0].message.content.strip()

    # Parse JSON response (handle potential markdown wrapping)
    if content.startswith("```"):
        content = content.split("\n", 1)[1].rsplit("```", 1)[0].strip()

    matches = json.loads(content)

    # Report token usage for cost transparency
    usage = response.usage
    if usage:
        input_cost = (usage.prompt_tokens / 1_000_000) * 0.15
        output_cost = (usage.completion_tokens / 1_000_000) * 0.60
        total_cost = input_cost + output_cost
        print(f"   Tokens: {usage.prompt_tokens} in / {usage.completion_tokens} out")
        print(f"   Cost: ~${total_cost:.4f}")

    return matches


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------


def display_matches(
    matches: list[dict],
    issues: list[IssueSummary],
    csv_path: Path,
) -> None:
    """Display matched issues in a readable format."""
    # Build lookup from the full CSV for URLs
    urls: dict[int, str] = {}
    with csv_path.open("r", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for i, row in enumerate(reader, start=1):
            urls[i] = row["url"]

    print(f"\n{'='*60}")
    print(f"  🎯 Top {len(matches)} Issues Matched to Your Profile")
    print(f"{'='*60}")

    for rank, match in enumerate(matches, start=1):
        idx = match["issue_number"]
        reason = match.get("reason", "")

        # Find the issue summary
        issue = next((iss for iss in issues if iss.index == idx), None)
        if not issue:
            continue

        url = urls.get(idx, "")
        print(f"\n  {rank}. {issue.title}")
        print(f"     Repo: {issue.repo} ({issue.stars}⭐)")
        print(f"     URL:  {url}")
        print(f"     Why:  {reason}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Match good first issues to your interests using GPT-4o-mini.",
    )
    parser.add_argument(
        "--csv",
        default=DEFAULT_CSV,
        help=f"Path to scraped issues CSV (default: {DEFAULT_CSV})",
    )
    parser.add_argument(
        "--top", "-n",
        type=int,
        default=DEFAULT_TOP_N,
        help=f"Number of matches to return (default: {DEFAULT_TOP_N})",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    csv_path = Path(args.csv)

    # Validate prerequisites
    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        print("❌ Error: OPENAI_API_KEY environment variable not set.", file=sys.stderr)
        print("   Export it: export OPENAI_API_KEY='sk-...'", file=sys.stderr)
        return 1

    if not csv_path.exists():
        print(f"❌ Error: CSV not found at '{csv_path}'.", file=sys.stderr)
        print("   Run scrape_good_first_issues.py first.", file=sys.stderr)
        return 1

    # Load issues
    issues = load_issues(csv_path)
    if not issues:
        print("❌ No issues found in CSV.", file=sys.stderr)
        return 1

    print(f"📋 Loaded {len(issues)} issues from {csv_path}")

    # Gather user preferences interactively
    profile = gather_user_profile()

    # Match using LLM (single call)
    try:
        matches = match_with_llm(profile, issues, args.top, api_key)
    except json.JSONDecodeError as exc:
        print(f"❌ Failed to parse LLM response: {exc}", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"❌ LLM API call failed: {exc}", file=sys.stderr)
        return 1

    # Display results
    display_matches(matches, issues, csv_path)

    return 0


if __name__ == "__main__":
    sys.exit(main())
